# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 50055aee76ad60320f002cc450e27b64a7d0b2e7238371b677289bcbbecd05cb38efde2bccf96229aa0a0f1c027b7e24ca38e37c64dd532da0b8f8481fab2460

test:
  secret_key_base: c503af4b28cd80132c28085eaa3789da9e961f20f61a153468d9cc5348fae7ba9d6fca3b8d650deaeff000d25516ba205aafc55afa581bb184158e70c67ad86c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
